### ISSUE TITLE
Comunidade no slack

### ISSUE THREAD

**Issue by gentildpinto** [amarildolucas/codamos#9]
[Essa comunidade no slack não existe!](https://codamosorg.slack.com/)
Dá sempre erro :/

**Comment by JoseCage** [comment]
> [Essa comunidade no slack não existe!](https://codamosorg.slack.com/)
> Dá sempre erro :/

Aqui vai o link para entrar: https://join.slack.com/t/codamoshq/shared_invite/zt-clqrcj4h-q0Q83FfE~duH0XS9IhIIrA

**Comment by gentildpinto** [comment]
> Aqui vai o link para entrar: https://join.slack.com/t/codamoshq/shared_invite/zt-clqrcj4h-q0Q83FfE~duH0XS9IhIIrA

Valeu :)

**Comment by JoseCage** [comment]
Disponha.
